export const TRACKS_FETCH_REQUEST = 'TRACKS_FETCH_REQUEST'
export const TRACKS_FETCH_SUCCESS = 'TRACKS_FETCH_SUCCESS'
export const TRACKS_FETCH_FAIL = 'TRACKS_FETCH_FAIL'
export const SET_NOW_PLAYING = 'SET_NOW_PLAYING'
